# Generated by Django 3.2.8 on 2023-03-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_verified'),
        ('property', '0001_initial'),
        ('settings', '0002_referens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_x_persona', models.FloatField(default=0.2)),
                ('porcentaje_subtotal_reservacion', models.FloatField(default=0.03)),
            ],
        ),
        migrations.CreateModel(
            name='Movement_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='History_Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.FloatField()),
                ('amount_me', models.FloatField()),
                ('amount_property', models.FloatField()),
                ('date_register', models.DateField(auto_now_add=True)),
                ('date_payment', models.DateField(auto_now_add=True)),
                ('propertys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
