# Generated by Django 3.2.8 on 2023-03-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_cancelled'),
        ('settings', '0003_history_transaccion_movement_history_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_transaccion',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
