# Generated by Django 3.2.8 on 2023-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(default=2),
        ),
    ]
