# Generated by Django 3.2.8 on 2023-03-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_cameras', models.BooleanField(default=False)),
                ('weapons', models.BooleanField(default=False)),
                ('dangerous_animals', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hosting_Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('street_optional', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('departament', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('discoun', models.FloatField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('price_clean', models.IntegerField(default=0)),
                ('price_entrada', models.IntegerField(default=0)),
                ('btn_clean', models.BooleanField(default=False)),
                ('cod_ref', models.IntegerField(default=0)),
                ('extras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='property.extras')),
                ('hosting_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosting_space', to='property.hosting_space')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('type_space', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='ImageCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Security_elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke_detector', models.BooleanField(default=False)),
                ('first_aid_kit', models.BooleanField(default=False)),
                ('fire_extinguisher', models.BooleanField(default=False)),
                ('carbon_monoxide_detector', models.BooleanField(default=False)),
                ('propertys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space', to='property.space'),
        ),
        migrations.AddField(
            model_name='property',
            name='tag_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_description', to='property.tag_description'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='user.user'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Gallery')),
                ('propertys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.IntegerField(blank=True, default=0, null=True)),
                ('room', models.IntegerField(blank=True, default=0, null=True)),
                ('beds', models.IntegerField(blank=True, default=0, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('paid_parking', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('work_zone', models.BooleanField(default=False)),
                ('propertys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Infomation_addtional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('terrace', models.BooleanField(default=False)),
                ('grill', models.BooleanField(default=False)),
                ('outdoor', models.BooleanField(default=False)),
                ('campfire_place', models.BooleanField(default=False)),
                ('pool_table', models.BooleanField(default=False)),
                ('indoor', models.BooleanField(default=False)),
                ('piano', models.BooleanField(default=False)),
                ('exersice', models.BooleanField(default=False)),
                ('lake', models.BooleanField(default=False)),
                ('beach', models.BooleanField(default=False)),
                ('entrace', models.BooleanField(default=False)),
                ('propertys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('propertys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
